server:
  port: 8123
  servlet:
    context-path: /api
spring:
    application:
      name: run-picture-backend
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/social_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
mybatis-plus:
  configuration:
    # mybatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境中打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  # 逻辑删除字段
      logic-delete-value: 1      # 逻辑删除值
      logic-not-delete-value: 0  # 逻辑未删除值
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    version: 1.0
    group:
      default:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.run.runpicturebackend.controller